import { createContext, ReactNode, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'ar';

type TranslationValue = string | ((params: Record<string, string | number>) => string);

const translations = {
  en: {
    common: {
      appName: 'Doleh Clinic',
      dashboard: 'Dashboard',
      patients: 'Patients',
      reports: 'Reports',
      reservations: 'Reservations',
      banners: 'News & Offers',
      logout: 'Logout',
      login: 'Login',
      save: 'Save',
      cancel: 'Cancel',
      email: 'Email',
      password: 'Password',
      signingIn: 'Signing in...',
      search: 'Search',
      actions: 'Actions',
      name: 'Name',
      id: 'ID',
      phone: 'Phone',
      age: 'Age',
      gender: 'Gender',
      address: 'Address',
      condition: 'Condition',
      notes: 'Notes',
      patient: 'Patient',
      patientId: 'Patient ID',
      reportId: 'Report ID',
      date: 'Date',
      time: 'Time',
      diagnosis: 'Diagnosis',
      treatmentPlan: 'Treatment Plan',
      sessionNotes: 'Session Notes',
      progress: 'Progress',
      attachments: 'Attachments',
      savePatient: 'Save Patient',
      saveReport: 'Save Report',
      saving: 'Saving...',
      addPatient: 'Add Patient',
      addReport: 'Add Report',
      visitWebsite: 'Visit Website',
      exportCsv: 'Export CSV',
      importCsv: 'Import CSV',
      downloadSample: 'Download Sample',
      editPatient: 'Edit Patient',
      editReport: 'Edit Report',
      view: 'View',
      accept: 'Accept',
      reject: 'Reject',
      noAttachments: 'No attachments.',
      notAvailable: 'N/A',
      male: 'Male',
      female: 'Female',
      improving: 'Improving',
      stable: 'Stable',
      worse: 'Worse',
      recentPatients: 'Recent Patients',
      totalPatients: 'Total patients',
      totalReports: 'Total reports',
      sortBy: 'Sort By',
      order: 'Order',
      descending: 'Descending',
      ascending: 'Ascending',
      createdDate: 'Created Date',
      lastVisit: 'Last Visit',
      allPatients: 'All Patients',
      dateFrom: 'Date From',
      dateTo: 'Date To',
      status: 'Status',
      language: 'Language',
      english: 'English',
      arabic: 'Arabic',
      unknownPatient: 'Unknown patient',
      darkMode: 'Dark',
      lightMode: 'Light',
      pending: 'Pending',
      accepted: 'Accepted',
      rejected: 'Rejected',
      importSuccess: ({ count }: Record<string, string | number>) => `${count} rows imported successfully.`,
      importFailed: 'CSV import failed.',
      importEmpty: 'No valid CSV rows found.',
      uploadCsvHint: 'Upload a CSV file with matching column names.'
    },
    loginPage: {
      title: 'Doleh Clinic',
      subtitle: 'Secure access for doctors and clinic administrators.'
    },
    dashboardPage: {
      subtitle: 'Overview of clinic activity and quick actions.',
      noPatientsTitle: 'No patients yet',
      noPatientsDescription: 'Add your first patient to start managing records.',
      lastVisitLabel: 'Last visit',
      reportsTrend: 'Reports Trend',
      progressOverview: 'Progress Overview',
      conditionsOverview: 'Condition Breakdown',
      reportsTrendSubtitle: 'Monthly reports created over the last six months.',
      progressOverviewSubtitle: 'Current spread of patient progress states.',
      conditionsOverviewSubtitle: 'Most common conditions across active patients.'
    },
    patientsPage: {
      subtitle: 'Search, review, and update patient records.',
      noPatientsTitle: 'No patients found',
      noPatientsDescription: 'Try adjusting the search filters or add a new patient.',
      foundCount: ({ count }: Record<string, string | number>) => `${count} patients found`,
      patientSubtitle: ({ condition }: Record<string, string | number>) => `Condition: ${condition}`,
      formSubtitle: 'Maintain accurate patient information for clinical follow-up.',
      reportsEmpty: 'No reports recorded for this patient yet.',
      deleteConfirm: ({ name }: Record<string, string | number>) => `Delete ${name}?`,
      fullName: 'Full Name'
    },
    reportsPage: {
      subtitle: 'Track clinical sessions, progress, and treatment plans.',
      formSubtitle: 'Capture diagnosis, treatment plan, and progress updates.',
      noReportsTitle: 'No reports found',
      noReportsDescription: 'Add a report or adjust the filters.',
      detailsTitle: 'Report Details',
      sessionDate: ({ date }: Record<string, string | number>) => `Session date: ${date}`,
      attachmentsHint: 'One URL per line',
      uploadFiles: 'Upload Files',
      uploading: 'Uploading...',
      uploadHint: 'Upload images or PDFs here, or paste URLs in the field beside it.',
      uploadFailed: 'Attachment upload failed.',
      detailsPatient: 'Patient',
      detailsDiagnosis: 'Diagnosis',
      detailsTreatment: 'Treatment Plan',
      detailsSessionNotes: 'Session Notes',
      detailsProgress: 'Progress'
    },
    reservationsPage: {
      adminSubtitle: 'Review patient requests, confirm time slots, and update decisions.',
      patientSubtitle: 'Request a reservation and follow your latest booking updates.',
      requestReservation: 'Request Reservation',
      addReservation: 'Add Reservation',
      newReservationTitle: 'New Reservation',
      reservationDateTime: 'Reservation Date & Time',
      adminNotes: 'Admin Notes',
      reviewedAt: 'Reviewed At',
      manageReservation: 'Manage Reservation',
      quickActions: 'Quick Actions',
      allStatuses: 'All Statuses',
      dateAvailabilityHint: 'Only Sunday to Thursday business dates with open slots can be selected.',
      selectDateFirst: 'Select a date first to see available times.',
      timeGapHint: 'Unavailable times are disabled to keep a 45-minute gap between reservations.',
      createSuccess: 'Reservation request submitted successfully.',
      updateSuccess: 'Reservation updated successfully.',
      noReservationsTitle: 'No reservations found',
      noReservationsDescription: 'There are no reservation requests matching the current filter.',
      noOwnReservationsTitle: 'No reservations yet',
      noOwnReservationsDescription: 'Submit your first reservation request to get started.',
      totalReservations: ({ count }: Record<string, string | number>) => `${count} reservations`
    },
    landingPage: {
      navHome: 'Home',
      navGallery: 'News & tips',
      navContact: 'Contact',
      galleryTitle: 'News & health tips',
      gallerySubtitle: 'Recent posts from Doleh Clinic. Tap any picture to view it full size.',
      galleryPoster: ({ number }: Record<string, string | number>) => `Doleh Clinic post ${number}`,
      galleryPrevious: 'Previous',
      galleryNext: 'Next',
      galleryClose: 'Close',
      contactTitle: 'Visit or call us',
      contactSubtitle: 'We are happy to answer your questions before you book.',
      callUs: 'Call us',
      phoneNumber: '0598440175',
      locationLabel: 'Our location',
      address: 'Sufyan Street / Sakhtian Building, 4th floor, Nablus, Palestine',
      openInMaps: 'Open in Maps',
      hoursLabel: 'Working days',
      followUs: 'Follow us',
      followUsHint: 'News, tips, and updates from the clinic.',
      facebookPage: 'Facebook page',
      whatsapp: 'WhatsApp',
      whatsappUs: 'Message us on WhatsApp',
      navServices: 'Services',
      navHowItWorks: 'How it works',
      navAvailability: 'Available times',
      navFaq: 'FAQ',
      navBook: 'Book now',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      dashboardLink: 'My account',
      staffLogin: 'Staff login',
      heroBadge: 'Physiotherapy & Rehabilitation',
      title: 'Move better. Feel better. Book in under a minute.',
      subtitle: 'Doleh Clinic helps you recover from pain and injury with personal treatment plans. Pick a free time and reserve your session online.',
      bookNow: 'Book a session',
      viewTimes: 'See available times',
      perkOnline: 'Easy online booking',
      perkPlans: 'Personal treatment plans',
      perkConfirm: 'Quick confirmation',
      perkBilingual: 'Arabic & English',
      liveStatus: 'Live clinic status',
      sessionRunningTitle: 'A session is running now',
      sessionRunningHint: 'Our therapist is with a patient at the moment. You can still book a later time.',
      clinicFreeTitle: 'No session is running right now',
      clinicFreeHint: 'The clinic is free at the moment. Choose a time below and we will take care of the rest.',
      statusUnavailable: 'Live status is not available right now.',
      bookedToday: ({ count }: Record<string, string | number>) => `${count} sessions booked today`,
      upcomingToday: ({ count }: Record<string, string | number>) => `${count} still to come today`,
      noBookingsToday: 'No bookings yet today',
      servicesTitle: 'How we can help',
      servicesSubtitle: 'Treatment for the most common causes of pain and limited movement.',
      serviceBackTitle: 'Back & neck pain',
      serviceBackText: 'Relief and posture correction for pain caused by desk work, lifting, or long-term strain.',
      serviceSportsTitle: 'Sports injuries',
      serviceSportsText: 'Safe recovery from sprains, strains, and ligament injuries, and a smooth return to activity.',
      serviceRehabTitle: 'Post-surgery rehabilitation',
      serviceRehabText: 'Guided exercises that rebuild strength and movement after operations and fractures.',
      serviceJointsTitle: 'Joint & arthritis care',
      serviceJointsText: 'Keep knees, shoulders, hips, and other joints moving comfortably.',
      serviceNeuroTitle: 'Nerve & muscle problems',
      serviceNeuroText: 'Support for weakness, numbness, and movement difficulties linked to nerves or muscles.',
      serviceElderlyTitle: 'Mobility & balance',
      serviceElderlyText: 'Exercises that improve balance and independence and lower the risk of falls.',
      howTitle: 'Booking is simple',
      howSubtitle: 'Three quick steps, no account needed.',
      step1Title: 'Choose a day and time',
      step1Text: 'Pick from the free times shown on this page.',
      step2Title: 'Tell us who you are',
      step2Text: 'Enter your name, phone number, and age.',
      step3Title: 'Get confirmed',
      step3Text: 'The clinic reviews your request and confirms your session.',
      availabilityTitle: 'Available times',
      availabilitySubtitle: 'Choose a day, then tap a free time to start your booking.',
      today: 'Today',
      tomorrow: 'Tomorrow',
      freeTimes: ({ count }: Record<string, string | number>) => `${count} free`,
      noFreeTimes: 'No free times left on this day. Please choose another day.',
      noDaysAvailable: 'There are no open days right now. Please check back soon.',
      tapToBook: 'Tap a time to book it',
      slotSelected: ({ date, time }: Record<string, string | number>) => `Selected: ${date} at ${time}`,
      reserveTitle: 'Reserve your session',
      reserveSubtitle: 'Enter your name, phone number, and preferred time to request a reservation.',
      reserveNote: 'Your details are only used to arrange your session.',
      faqTitle: 'Common questions',
      faqSubtitle: 'Quick answers before you book.',
      faq1Q: 'Do I need an account to book?',
      faq1A: 'No. Just enter your name, phone number, and age, choose a free time, and send your request.',
      faq2Q: 'How do I know my booking is confirmed?',
      faq2A: 'The clinic reviews each request and confirms it. Keep your phone nearby in case we need to contact you.',
      faq3Q: 'Which days can I book?',
      faq3A: 'Sunday to Thursday. The calendar only lets you pick days that still have free times.',
      faq4Q: 'How long is a session?',
      faq4A: 'Sessions are spaced 45 minutes apart, so each booking has its own dedicated time.',
      faq5Q: 'Is my information private?',
      faq5A: 'Yes. This page never shows any patient details, only whether a session is running and which times are free.',
      footerTagline: 'Physiotherapy & rehabilitation care you can trust.',
      footerDays: 'Sunday – Thursday',
      footerLinks: 'Quick links',
      footerHours: 'Working days',
      footerRights: ({ year }: Record<string, string | number>) => `© ${year} Doleh Clinic. All rights reserved.`,
      backToTop: 'Back to top'
    },
    bannersPage: {
      subtitle: 'Manage the scrolling news and offers banner shown on the landing and main pages.',
      addBanner: 'Add Banner',
      editBanner: 'Edit Banner',
      messageEn: 'Message (English)',
      messageAr: 'Message (Arabic)',
      order: 'Order',
      active: 'Active',
      inactive: 'Inactive',
      deleteConfirm: 'Delete this banner?',
      noBannersTitle: 'No banners yet',
      noBannersDescription: 'Add a banner to show news or offers on the landing and main pages.'
    },
    validation: {
      validEmail: 'Valid email is required',
      passwordMin: 'Password must be at least 6 characters',
      nameRequired: 'Name is required',
      phoneRequired: 'Phone is required',
      ageRequired: 'Age is required',
      conditionRequired: 'Condition is required',
      patientRequired: 'Patient is required',
      dateRequired: 'Date is required',
      diagnosisRequired: 'Diagnosis is required',
      treatmentPlanRequired: 'Treatment plan is required',
      sessionNotesRequired: 'Session notes are required',
      messageEnRequired: 'English message is required',
      messageArRequired: 'Arabic message is required'
    }
  },
  ar: {
    common: {
      appName: 'Doleh Clinic',
      dashboard: 'لوحة التحكم',
      patients: 'المرضى',
      reports: 'التقارير',
      reservations: 'الحجوزات',
      banners: 'الأخبار والعروض',
      logout: 'تسجيل الخروج',
      login: 'تسجيل الدخول',
      save: 'حفظ',
      cancel: 'إلغاء',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      signingIn: 'جاري تسجيل الدخول...',
      search: 'بحث',
      actions: 'الإجراءات',
      name: 'الاسم',
      id: 'المعرف',
      phone: 'الهاتف',
      age: 'العمر',
      gender: 'الجنس',
      address: 'العنوان',
      condition: 'الحالة',
      notes: 'ملاحظات',
      patient: 'المريض',
      patientId: 'معرف المريض',
      reportId: 'معرف التقرير',
      date: 'التاريخ',
      time: 'الوقت',
      diagnosis: 'التشخيص',
      treatmentPlan: 'الخطة العلاجية',
      sessionNotes: 'ملاحظات الجلسة',
      progress: 'التقدم',
      attachments: 'المرفقات',
      savePatient: 'حفظ المريض',
      saveReport: 'حفظ التقرير',
      saving: 'جاري الحفظ...',
      addPatient: 'إضافة مريض',
      addReport: 'إضافة تقرير',
      visitWebsite: 'زيارة الموقع',
      exportCsv: 'تصدير CSV',
      importCsv: 'استيراد CSV',
      downloadSample: 'تنزيل نموذج',
      editPatient: 'تعديل المريض',
      editReport: 'تعديل التقرير',
      view: 'عرض',
      accept: 'قبول',
      reject: 'رفض',
      noAttachments: 'لا توجد مرفقات.',
      notAvailable: 'غير متوفر',
      male: 'ذكر',
      female: 'أنثى',
      improving: 'تحسن',
      stable: 'مستقر',
      worse: 'تدهور',
      recentPatients: 'أحدث المرضى',
      totalPatients: 'إجمالي المرضى',
      totalReports: 'إجمالي التقارير',
      sortBy: 'الترتيب حسب',
      order: 'الترتيب',
      descending: 'تنازلي',
      ascending: 'تصاعدي',
      createdDate: 'تاريخ الإنشاء',
      lastVisit: 'آخر زيارة',
      allPatients: 'كل المرضى',
      dateFrom: 'من تاريخ',
      dateTo: 'إلى تاريخ',
      status: 'الحالة',
      language: 'اللغة',
      english: 'الإنجليزية',
      arabic: 'العربية',
      unknownPatient: 'مريض غير معروف',
      darkMode: 'داكن',
      lightMode: 'فاتح',
      pending: 'قيد الانتظار',
      accepted: 'مقبول',
      rejected: 'مرفوض',
      importSuccess: ({ count }: Record<string, string | number>) => `تم استيراد ${count} صف بنجاح.`,
      importFailed: 'فشل استيراد ملف CSV.',
      importEmpty: 'لم يتم العثور على صفوف CSV صالحة.',
      uploadCsvHint: 'ارفع ملف CSV بأسماء أعمدة مطابقة.'
    },
    loginPage: {
      title: 'Doleh Clinic',
      subtitle: 'وصول آمن للأطباء وإداريي العيادة.'
    },
    dashboardPage: {
      subtitle: 'نظرة عامة على نشاط العيادة والإجراءات السريعة.',
      noPatientsTitle: 'لا يوجد مرضى بعد',
      noPatientsDescription: 'أضف أول مريض لبدء إدارة السجلات.',
      lastVisitLabel: 'آخر زيارة',
      reportsTrend: 'اتجاه التقارير',
      progressOverview: 'نظرة على التقدم',
      conditionsOverview: 'توزيع الحالات',
      reportsTrendSubtitle: 'عدد التقارير التي أُنشئت خلال آخر ستة أشهر.',
      progressOverviewSubtitle: 'التوزيع الحالي لحالات تقدم المرضى.',
      conditionsOverviewSubtitle: 'أكثر الحالات شيوعًا بين المرضى الحاليين.'
    },
    patientsPage: {
      subtitle: 'ابحث وراجع وحدّث سجلات المرضى.',
      noPatientsTitle: 'لم يتم العثور على مرضى',
      noPatientsDescription: 'جرّب تعديل عوامل البحث أو أضف مريضًا جديدًا.',
      foundCount: ({ count }: Record<string, string | number>) => `تم العثور على ${count} مريض`,
      patientSubtitle: ({ condition }: Record<string, string | number>) => `الحالة: ${condition}`,
      formSubtitle: 'حافظ على بيانات المريض الدقيقة للمتابعة السريرية.',
      reportsEmpty: 'لا توجد تقارير مسجلة لهذا المريض بعد.',
      deleteConfirm: ({ name }: Record<string, string | number>) => `هل تريد حذف ${name}؟`,
      fullName: 'الاسم الكامل'
    },
    reportsPage: {
      subtitle: 'تابع الجلسات العلاجية والتقدم والخطط العلاجية.',
      formSubtitle: 'سجّل التشخيص والخطة العلاجية وتحديثات التقدم.',
      noReportsTitle: 'لم يتم العثور على تقارير',
      noReportsDescription: 'أضف تقريرًا أو عدّل عوامل التصفية.',
      detailsTitle: 'تفاصيل التقرير',
      sessionDate: ({ date }: Record<string, string | number>) => `تاريخ الجلسة: ${date}`,
      attachmentsHint: 'رابط واحد في كل سطر',
      uploadFiles: 'رفع ملفات',
      uploading: 'جارٍ الرفع...',
      uploadHint: 'ارفع الصور أو ملفات PDF هنا، أو الصق الروابط في الحقل المجاور.',
      uploadFailed: 'فشل رفع المرفقات.',
      detailsPatient: 'المريض',
      detailsDiagnosis: 'التشخيص',
      detailsTreatment: 'الخطة العلاجية',
      detailsSessionNotes: 'ملاحظات الجلسة',
      detailsProgress: 'التقدم'
    },
    reservationsPage: {
      adminSubtitle: 'راجع طلبات المرضى وحدد المواعيد وحدّث القرار.',
      patientSubtitle: 'اطلب حجزًا وتابع آخر تحديثات الموعد الخاص بك.',
      requestReservation: 'طلب حجز',
      addReservation: 'إضافة حجز',
      newReservationTitle: 'حجز جديد',
      reservationDateTime: 'تاريخ ووقت الحجز',
      adminNotes: 'ملاحظات الإدارة',
      reviewedAt: 'تاريخ المراجعة',
      manageReservation: 'إدارة الحجز',
      quickActions: 'إجراءات سريعة',
      allStatuses: 'كل الحالات',
      dateAvailabilityHint: 'يمكن اختيار أيام العمل من الأحد إلى الخميس فقط إذا كانت تحتوي على مواعيد متاحة.',
      selectDateFirst: 'اختر التاريخ أولاً لعرض الأوقات المتاحة.',
      timeGapHint: 'الأوقات غير المتاحة معطلة للحفاظ على فجوة 45 دقيقة بين الحجوزات.',
      createSuccess: 'تم إرسال طلب الحجز بنجاح.',
      updateSuccess: 'تم تحديث الحجز بنجاح.',
      noReservationsTitle: 'لا توجد حجوزات',
      noReservationsDescription: 'لا توجد طلبات حجز تطابق عامل التصفية الحالي.',
      noOwnReservationsTitle: 'لا توجد حجوزات بعد',
      noOwnReservationsDescription: 'أرسل أول طلب حجز للبدء.',
      totalReservations: ({ count }: Record<string, string | number>) => `${count} حجوزات`
    },
    landingPage: {
      navHome: 'الرئيسية',
      navGallery: 'أخبار ونصائح',
      navContact: 'تواصل معنا',
      galleryTitle: 'أخبار ونصائح صحية',
      gallerySubtitle: 'آخر منشورات مركز الدوله. اضغط على أي صورة لعرضها بالحجم الكامل.',
      galleryPoster: ({ number }: Record<string, string | number>) => `منشور مركز الدوله رقم ${number}`,
      galleryPrevious: 'السابق',
      galleryNext: 'التالي',
      galleryClose: 'إغلاق',
      contactTitle: 'زرنا أو اتصل بنا',
      contactSubtitle: 'يسعدنا الإجابة عن أسئلتك قبل الحجز.',
      callUs: 'اتصل بنا',
      phoneNumber: '0598440175',
      locationLabel: 'موقعنا',
      address: 'شارع سفيان / عمارة سختيان، الطابق الرابع، نابلس، فلسطين',
      openInMaps: 'فتح في الخريطة',
      hoursLabel: 'أيام العمل',
      followUs: 'تابعنا',
      followUsHint: 'أخبار ونصائح وتحديثات من المركز.',
      facebookPage: 'صفحة فيسبوك',
      whatsapp: 'واتساب',
      whatsappUs: 'راسلنا عبر واتساب',
      navServices: 'خدماتنا',
      navHowItWorks: 'كيف يعمل الحجز',
      navAvailability: 'المواعيد المتاحة',
      navFaq: 'الأسئلة الشائعة',
      navBook: 'احجز الآن',
      openMenu: 'فتح القائمة',
      closeMenu: 'إغلاق القائمة',
      dashboardLink: 'حسابي',
      staffLogin: 'دخول الموظفين',
      heroBadge: 'العلاج الطبيعي والتأهيل',
      title: 'تحرّك بأفضل حال. اشعر بالراحة. احجز في أقل من دقيقة.',
      subtitle: 'يساعدك مركز الدوله على التعافي من الألم والإصابات بخطط علاج خاصة بك. اختر وقتًا متاحًا واحجز جلستك عبر الإنترنت.',
      bookNow: 'احجز جلسة',
      viewTimes: 'عرض المواعيد المتاحة',
      perkOnline: 'حجز سهل عبر الإنترنت',
      perkPlans: 'خطط علاج شخصية',
      perkConfirm: 'تأكيد سريع',
      perkBilingual: 'عربي وإنجليزي',
      liveStatus: 'حالة العيادة الآن',
      sessionRunningTitle: 'هناك جلسة جارية الآن',
      sessionRunningHint: 'المعالج مع مريض في الوقت الحالي. ما زال بإمكانك حجز موعد لاحق.',
      clinicFreeTitle: 'لا توجد جلسة جارية الآن',
      clinicFreeHint: 'العيادة متاحة حاليًا. اختر وقتًا من الأسفل وسنتكفّل بالباقي.',
      statusUnavailable: 'حالة العيادة المباشرة غير متاحة حاليًا.',
      bookedToday: ({ count }: Record<string, string | number>) => `${count} جلسات محجوزة اليوم`,
      upcomingToday: ({ count }: Record<string, string | number>) => `${count} جلسات قادمة اليوم`,
      noBookingsToday: 'لا توجد حجوزات اليوم بعد',
      servicesTitle: 'كيف يمكننا مساعدتك',
      servicesSubtitle: 'علاج لأكثر أسباب الألم وصعوبة الحركة شيوعًا.',
      serviceBackTitle: 'آلام الظهر والرقبة',
      serviceBackText: 'تخفيف الألم وتصحيح الوضعية الناتج عن العمل المكتبي أو الرفع أو الإجهاد المزمن.',
      serviceSportsTitle: 'الإصابات الرياضية',
      serviceSportsText: 'تعافٍ آمن من الالتواءات والشدّ وإصابات الأربطة، وعودة سلسة إلى النشاط.',
      serviceRehabTitle: 'التأهيل بعد العمليات',
      serviceRehabText: 'تمارين موجّهة لاستعادة القوة والحركة بعد العمليات والكسور.',
      serviceJointsTitle: 'المفاصل والتهاب المفاصل',
      serviceJointsText: 'حافظ على حركة الركبة والكتف والورك وبقية المفاصل براحة.',
      serviceNeuroTitle: 'مشاكل الأعصاب والعضلات',
      serviceNeuroText: 'دعم لحالات الضعف والتنميل وصعوبات الحركة المرتبطة بالأعصاب أو العضلات.',
      serviceElderlyTitle: 'الحركة والتوازن',
      serviceElderlyText: 'تمارين تحسّن التوازن والاستقلالية وتقلل خطر السقوط.',
      howTitle: 'الحجز بسيط',
      howSubtitle: 'ثلاث خطوات سريعة، بدون إنشاء حساب.',
      step1Title: 'اختر اليوم والوقت',
      step1Text: 'اختر من الأوقات المتاحة المعروضة في هذه الصفحة.',
      step2Title: 'عرّفنا بنفسك',
      step2Text: 'أدخل اسمك ورقم هاتفك وعمرك.',
      step3Title: 'احصل على التأكيد',
      step3Text: 'تراجع العيادة طلبك وتؤكد جلستك.',
      availabilityTitle: 'المواعيد المتاحة',
      availabilitySubtitle: 'اختر يومًا ثم اضغط على وقت متاح لبدء الحجز.',
      today: 'اليوم',
      tomorrow: 'غدًا',
      freeTimes: ({ count }: Record<string, string | number>) => `${count} متاح`,
      noFreeTimes: 'لا توجد أوقات متاحة في هذا اليوم. يرجى اختيار يوم آخر.',
      noDaysAvailable: 'لا توجد أيام متاحة حاليًا. يرجى المحاولة لاحقًا.',
      tapToBook: 'اضغط على وقت لحجزه',
      slotSelected: ({ date, time }: Record<string, string | number>) => `تم اختيار: ${date} الساعة ${time}`,
      reserveTitle: 'احجز جلستك',
      reserveSubtitle: 'أدخل اسمك ورقم هاتفك والوقت المناسب لطلب الحجز.',
      reserveNote: 'نستخدم بياناتك فقط لترتيب جلستك.',
      faqTitle: 'أسئلة شائعة',
      faqSubtitle: 'إجابات سريعة قبل الحجز.',
      faq1Q: 'هل أحتاج إلى حساب للحجز؟',
      faq1A: 'لا. أدخل اسمك ورقم هاتفك وعمرك، واختر وقتًا متاحًا، ثم أرسل طلبك.',
      faq2Q: 'كيف أعرف أن حجزي تم تأكيده؟',
      faq2A: 'تراجع العيادة كل طلب وتؤكده. أبقِ هاتفك قريبًا تحسبًا لتواصلنا معك.',
      faq3Q: 'ما الأيام التي يمكنني الحجز فيها؟',
      faq3A: 'من الأحد إلى الخميس. يسمح لك التقويم باختيار الأيام التي ما زالت فيها أوقات متاحة فقط.',
      faq4Q: 'كم مدة الجلسة؟',
      faq4A: 'تفصل بين الجلسات 45 دقيقة، ليحصل كل حجز على وقته الخاص.',
      faq5Q: 'هل معلوماتي خاصة؟',
      faq5A: 'نعم. لا تعرض هذه الصفحة أي بيانات عن المرضى، فقط ما إذا كانت هناك جلسة جارية والأوقات المتاحة.',
      footerTagline: 'رعاية علاج طبيعي وتأهيل تثق بها.',
      footerDays: 'من الأحد إلى الخميس',
      footerLinks: 'روابط سريعة',
      footerHours: 'أيام العمل',
      footerRights: ({ year }: Record<string, string | number>) => `© ${year} مركز الدوله. جميع الحقوق محفوظة.`,
      backToTop: 'العودة للأعلى'
    },
    bannersPage: {
      subtitle: 'إدارة شريط الأخبار والعروض المتحرك الذي يظهر في صفحة الهبوط والصفحة الرئيسية.',
      addBanner: 'إضافة إعلان',
      editBanner: 'تعديل الإعلان',
      messageEn: 'النص (بالإنجليزية)',
      messageAr: 'النص (بالعربية)',
      order: 'الترتيب',
      active: 'مفعّل',
      inactive: 'غير مفعّل',
      deleteConfirm: 'هل تريد حذف هذا الإعلان؟',
      noBannersTitle: 'لا توجد إعلانات بعد',
      noBannersDescription: 'أضف إعلانًا لعرض الأخبار أو العروض في صفحة الهبوط والصفحة الرئيسية.'
    },
    validation: {
      validEmail: 'يرجى إدخال بريد إلكتروني صحيح',
      passwordMin: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      nameRequired: 'الاسم مطلوب',
      phoneRequired: 'الهاتف مطلوب',
      ageRequired: 'العمر مطلوب',
      conditionRequired: 'الحالة مطلوبة',
      patientRequired: 'المريض مطلوب',
      dateRequired: 'التاريخ مطلوب',
      diagnosisRequired: 'التشخيص مطلوب',
      treatmentPlanRequired: 'الخطة العلاجية مطلوبة',
      sessionNotesRequired: 'ملاحظات الجلسة مطلوبة',
      messageEnRequired: 'النص الإنجليزي مطلوب',
      messageArRequired: 'النص العربي مطلوب'
    }
  }
} as const;

type TranslationKey = `${keyof typeof translations.en}.${string}`;

interface LanguageContextValue {
  language: Language;
  direction: 'ltr' | 'rtl';
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

export const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const getNestedValue = (language: Language, key: TranslationKey): TranslationValue | undefined => {
  const segments = key.split('.');
  let current: unknown = translations[language];

  for (const segment of segments) {
    if (typeof current !== 'object' || current === null || !(segment in current)) {
      return undefined;
    }
    current = (current as Record<string, unknown>)[segment];
  }

  return current as TranslationValue | undefined;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('app_language');
    return stored === 'ar' ? 'ar' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      direction: language === 'ar' ? 'rtl' : 'ltr',
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'ar' : 'en')),
      t: (key, params = {}) => {
        const valueForKey = getNestedValue(language, key) || getNestedValue('en', key);
        if (typeof valueForKey === 'function') {
          return valueForKey(params);
        }
        return valueForKey || key;
      }
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
